server:
  port: 8777
  ssl:
    enabled: true
    key-store: keystore.p12
    key-store-password: ENC(cpQ+q/0TnonX8QedCpj+tpAE1FHKxcU7)
    key-store-type: PKCS12
    key-alias: bns-ssl

spring:
  cache:
    type: redis
  profiles:
    include:
      - core
  kafka:
    bootstrap-servers: localhost:9092
  mail:
    host: smtp.naver.com
    port: 465
    username: ENC(R10y444N+ldfup9yMIm/csMUrc5HhA2q)
    password: ENC(g0EzZ5WEs7kwUn2d8f4Q5gGneyXtpvnC)
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          ssl:
            enable: true
            check-server-identity: true
            trust: smtp.naver.com
            socketFactory.class: javax.net.ssl.SSLSocketFactory
        debug: true
  redis:
    cache:
      host: localhost
      port: 6379