server:
  port: 8888

spring:
  profiles:
    include:
      - core
  kafka:
    bootstrap-servers: localhost:9092
  redis:
    host: localhost
    port: 6379

#logging:
#  level:
#    org:
#      hibernate:
#        type:
#          descriptor:
#            sql:
#              BasicBinder: TRACE
#        SQL: DEBUG