spring:
  datasource:
    url: ENC(blxv5FL3aLLx/XVEYQdlDQN2BXa/0kDZKlW0u6lJKSRNGo2qdPI32uk5u+CRRQyB1vl9VM0Vr4xaoXxAe9Vx6kxEIIfJFoW45rEvgRRkhl3P9kNHJS5EqTMI2zNe1JZ6av1uuscyd6BL2PDgChD+jNaZDfk85zfOsFGxXUlQ/RcybMJpOYNFog==)
    username: ENC(R5AJccsuYvkxzDz0Qujmpw==)
    password: ENC(M7vu/MqSo5KWnebV+9ZlI4B/bLmaVBrW)
  jpa:
    generate-ddl: true
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: false #sql 문이 보이도록
        dialect: org.hibernate.dialect.MySQL8Dialect
        connection:
          charSet: UTF-8 # 인코딩 설정

# jasypt
jasypt:
  encryptor:
    bean: jasyptStringEncryptor

file:
  dir: D:\jpshoppingmall\jpshoppingmall\images