spring:
  datasource:
    url: jdbc:mysql://localhost:3306/jpshoppingmall?rewriteBatchedStatements=true&characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: root
    password: 05Wogmlbbt!
  jpa:
    generate-ddl: true
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: false #sql 문이 보이도록
        dialect: org.hibernate.dialect.MySQL8Dialect
        connection:
          charSet: UTF-8 # 인코딩 설정

file:
  dir: D:\jpshoppingmall\jpshoppingmall\images