server:
  port: 8999

spring:
  profiles:
    include:
      - core
  kafka:
    bootstrap-servers: localhost:9092
  redis:
    notification:
      host: localhost
      port: 6381

#logging:
#  level:
#    org:
#      hibernate:
#        type:
#          descriptor:
#            sql:
#              BasicBinder: TRACE
#        SQL: DEBUG