spring:
  profiles:
    include:
      - core
  kafka:
    bootstrap-servers: localhost:9092
  cache:
    type: redis
  session:
    storage-type: redis
  redis:
    cache:
      host: localhost
      port: 6379
    session:
      host: localhost
      port: 6380

#logging:
#  level:
#    org:
#      hibernate:
#        type:
#          descriptor:
#            sql:
#              BasicBinder: TRACE
#        SQL: DEBUG

test-login: true
